name: example
description: Example for sizer plugin

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  sizer_pro:
    path: ../
  smooth_page_indicator: ^1.1.0
  google_fonts: ^4.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - images/
